package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class RamenDetail extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.id
     *
     * @mbggenerated 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.ramen_id
     *
     * @mbggenerated 
     */
    private Long ramenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.date
     *
     * @mbggenerated 
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.type
     *
     * @mbggenerated 
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.title
     *
     * @mbggenerated 
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.detail
     *
     * @mbggenerated 
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.publish_start
     *
     * @mbggenerated 
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.publish_end
     *
     * @mbggenerated 
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.create_datetime
     *
     * @mbggenerated 
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.update_datetime
     *
     * @mbggenerated 
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.del_flg
     *
     * @mbggenerated 
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen_detail.note
     *
     * @mbggenerated 
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.id
     *
     * @return the value of ramen_detail.id
     *
     * @mbggenerated 
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.id
     *
     * @param id the value for ramen_detail.id
     *
     * @mbggenerated 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.ramen_id
     *
     * @return the value of ramen_detail.ramen_id
     *
     * @mbggenerated 
     */
    public Long getRamenId() {
        return ramenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.ramen_id
     *
     * @param ramenId the value for ramen_detail.ramen_id
     *
     * @mbggenerated 
     */
    public void setRamenId(Long ramenId) {
        this.ramenId = ramenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.date
     *
     * @return the value of ramen_detail.date
     *
     * @mbggenerated 
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.date
     *
     * @param date the value for ramen_detail.date
     *
     * @mbggenerated 
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.type
     *
     * @return the value of ramen_detail.type
     *
     * @mbggenerated 
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.type
     *
     * @param type the value for ramen_detail.type
     *
     * @mbggenerated 
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.title
     *
     * @return the value of ramen_detail.title
     *
     * @mbggenerated 
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.title
     *
     * @param title the value for ramen_detail.title
     *
     * @mbggenerated 
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.detail
     *
     * @return the value of ramen_detail.detail
     *
     * @mbggenerated 
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.detail
     *
     * @param detail the value for ramen_detail.detail
     *
     * @mbggenerated 
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.publish_start
     *
     * @return the value of ramen_detail.publish_start
     *
     * @mbggenerated 
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.publish_start
     *
     * @param publishStart the value for ramen_detail.publish_start
     *
     * @mbggenerated 
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.publish_end
     *
     * @return the value of ramen_detail.publish_end
     *
     * @mbggenerated 
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.publish_end
     *
     * @param publishEnd the value for ramen_detail.publish_end
     *
     * @mbggenerated 
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.create_datetime
     *
     * @return the value of ramen_detail.create_datetime
     *
     * @mbggenerated 
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.create_datetime
     *
     * @param createDatetime the value for ramen_detail.create_datetime
     *
     * @mbggenerated 
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.update_datetime
     *
     * @return the value of ramen_detail.update_datetime
     *
     * @mbggenerated 
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.update_datetime
     *
     * @param updateDatetime the value for ramen_detail.update_datetime
     *
     * @mbggenerated 
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.del_flg
     *
     * @return the value of ramen_detail.del_flg
     *
     * @mbggenerated 
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.del_flg
     *
     * @param delFlg the value for ramen_detail.del_flg
     *
     * @mbggenerated 
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen_detail.note
     *
     * @return the value of ramen_detail.note
     *
     * @mbggenerated 
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen_detail.note
     *
     * @param note the value for ramen_detail.note
     *
     * @mbggenerated 
     */
    public void setNote(String note) {
        this.note = note;
    }
}