package jp.co.vermore.entity;

import jp.co.vermore.common.mvc.BaseEntity;

import java.util.Date;

public class Ramen extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.id
     *
     * @mbggenerated 
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.uuid
     *
     * @mbggenerated 
     */
    private String uuid;



    private Integer entryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.date
     *
     * @mbggenerated 
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.type
     *
     * @mbggenerated 
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.title
     *
     * @mbggenerated 
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.excerpt
     *
     * @mbggenerated 
     */
    private String excerpt;

    private int sortScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.publish_start
     *
     * @mbggenerated 
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.publish_end
     *
     * @mbggenerated 
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.create_datetime
     *
     * @mbggenerated 
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.update_datetime
     *
     * @mbggenerated 
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.del_flg
     *
     * @mbggenerated 
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ramen.note
     *
     * @mbggenerated 
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.id
     *
     * @return the value of ramen.id
     *
     * @mbggenerated 
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.id
     *
     * @param id the value for ramen.id
     *
     * @mbggenerated 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.uuid
     *
     * @return the value of ramen.uuid
     *
     * @mbggenerated 
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.uuid
     *
     * @param uuid the value for ramen.uuid
     *
     * @mbggenerated 
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.date
     *
     * @return the value of ramen.date
     *
     * @mbggenerated 
     */

    public Integer getEntryType() {
        return entryType;
    }

    public void setEntryType(Integer entryType) {
        this.entryType = entryType;
    }

    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.date
     *
     * @param date the value for ramen.date
     *
     * @mbggenerated 
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.type
     *
     * @return the value of ramen.type
     *
     * @mbggenerated 
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.type
     *
     * @param type the value for ramen.type
     *
     * @mbggenerated 
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.title
     *
     * @return the value of ramen.title
     *
     * @mbggenerated 
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.title
     *
     * @param title the value for ramen.title
     *
     * @mbggenerated 
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.excerpt
     *
     * @return the value of ramen.excerpt
     *
     * @mbggenerated 
     */
    public String getExcerpt() {
        return excerpt;
    }

    public int getSortScore() { return sortScore; }

    public void setSortScore(int sortScore) { this.sortScore = sortScore; }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.excerpt
     *
     * @param excerpt the value for ramen.excerpt
     *
     * @mbggenerated 
     */
    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.publish_start
     *
     * @return the value of ramen.publish_start
     *
     * @mbggenerated 
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.publish_start
     *
     * @param publishStart the value for ramen.publish_start
     *
     * @mbggenerated 
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.publish_end
     *
     * @return the value of ramen.publish_end
     *
     * @mbggenerated 
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.publish_end
     *
     * @param publishEnd the value for ramen.publish_end
     *
     * @mbggenerated 
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.create_datetime
     *
     * @return the value of ramen.create_datetime
     *
     * @mbggenerated 
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.create_datetime
     *
     * @param createDatetime the value for ramen.create_datetime
     *
     * @mbggenerated 
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.update_datetime
     *
     * @return the value of ramen.update_datetime
     *
     * @mbggenerated 
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.update_datetime
     *
     * @param updateDatetime the value for ramen.update_datetime
     *
     * @mbggenerated 
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.del_flg
     *
     * @return the value of ramen.del_flg
     *
     * @mbggenerated 
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.del_flg
     *
     * @param delFlg the value for ramen.del_flg
     *
     * @mbggenerated 
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ramen.note
     *
     * @return the value of ramen.note
     *
     * @mbggenerated 
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ramen.note
     *
     * @param note the value for ramen.note
     *
     * @mbggenerated 
     */
    public void setNote(String note) {
        this.note = note;
    }
}